microsoft/MixedReality-WorldLockingTools-Unity

- DocGen/Documentation/HowTos/InitialSetup.md
Emphasize necessity of NuGet for Unity to acquire FW Engine DLL.
> NuGet note

- Assets/WorldLocking.Examples/Scripts/AlignSubtree.cs
- Assets/WorldLocking.Examples/Scripts/PinManipulator.cs
Added some comments and a useful null check.
> Comment sub script

- DocGen/Documentation/Concepts/Advanced/CoordinateSpaces.md
- DocGen/Documentation/Concepts/Advanced/SpacePins.md
- DocGen/Documentation/Concepts/AdvancedConcepts.md
- DocGen/Documentation/HowTos.md
- DocGen/Documentation/HowTos/InitialSetup.md
- DocGen/Documentation/HowTos/SampleApplications.md
- DocGen/Documentation/HowTos/Tools.md
- DocGen/Documentation/HowTos/Troubleshooting.md
- DocGen/Documentation/toc.yml
Improved documentation on the Tools and Visualizations packaged with World Locking Tools.
Fixes #37 
Fixes #46
> Tools documentation

- Assets/WorldLocking.Core/Scripts/AlignSubtree.cs
- DocGen/Documentation/HowTos/InitialSetup.md
Points to a tutorial in the new sibling Samples repo.
> Point setup documentation to tutorial

- Assets/WorldLocking.Core/Scripts/AlignSubtree.cs
- DocGen/Documentation/Concepts/Advanced/SpacePins.md
A few trivial improvements to check that pipelines are still working after authentication changes.
> Docs check

- Assets/MRTK/Providers/WindowsMixedReality/XRSDK/Microsoft.MixedReality.Toolkit.Providers.XRSDK.WMR.asmdef
- Assets/MRTK/Providers/XRSDK/Microsoft.MixedReality.Toolkit.Providers.XRSDK.asmdef
- Assets/MRTK/SDK/Features/Input/Handlers/Manipulation/ManipulationHandler.cs
- Assets/MRTK/SDK/StandardAssets/Sprites/DefaultIconsSpriteSheet.psd.meta
- Assets/MixedRealityToolkit.Generated.meta
- Assets/MixedRealityToolkit.Generated/MRTK.Generated.sentinel.meta
- Assets/MixedRealityToolkit.Generated/ProjectPreferences.asset
- Assets/MixedRealityToolkit.Generated/ProjectPreferences.asset.meta
- Assets/WorldLocking.Core/Scripts/WorldLockingManager.cs
- ProjectSettings/EditorSettings.asset
- ProjectSettings/ProjectSettings.asset
- ProjectSettings/ProjectVersion.txt
- ProjectSettings/XRSettings.asset
Add a null check consistent with other null checks on rotateConstraint.
> Add Null check in ManipulationHandler

- DocGen/Documentation/HowTos/Troubleshooting.md
Better warnings for neglecting to install the FW Engine DLL.
> Extra trouble-shooting tips.

- DocGen/Documentation/HowTos/InitialSetup.md
- DocGen/Documentation/HowTos/Troubleshooting.md
- DocGen/Documentation/HowTos/UsingWLT/JustWorldLock.md
Document how to manually install Frozen World Engine DLL from NuGet.org if the client doesn't want to use NuGet For Unity.
> Update documentation 

- DocGen/Documentation/Concepts.md
- DocGen/Documentation/GettingStartedWithWorldLocking.md
- DocGen/Documentation/HowTos/XRSDK.md
- DocGen/Documentation/toc.yml
* Add links to orphaned pages.
* Also documents XR plugin versions tested.
Fixes: #96 
Fixes: #98 
Fixes: #86
> Documentation improvements

- Assets/WorldLocking.Tests/Core/Prefabs/IndiePinsRoot.prefab
- Assets/WorldLocking.Tests/Core/Scripts/TriangulatorTest.cs
And enhance output on failed time test.
> Fix weird corruption in prefab.

- Assets/WorldLocking.Core/Scripts/ARCore/AnchorManagerARCore.cs
- Assets/WorldLocking.Core/Scripts/WorldLockingManager.cs
- Assets/WorldLocking.Tests/Core/Scripts/SaveLoadTest.cs
- Assets/WorldLocking.Tests/Core/Scripts/WorldLockingManagerTest.cs
This brings support for applications using ARCore SDK directly (bypassing XRSDK ARCore plugin) up to the level of plausible. Further testing and validation necessary before release.
> Further testing, validation, and fixes for ARCore

- Assets/NuGet.config
- Assets/WorldLocking.Core/Scripts/WorldLockingManager.cs
Includes fix for XR SDK anchors (removing old workaround).
> Up version, potentially next release.

- Assets/MRTK/Providers/XRSDK/GenericXRSDKSpatialMeshObserver.cs
- Assets/WorldLocking.Core/Scripts/WorldLockingManager.cs
- UPM/core_files/package.json
- UPM/samples_files/CHANGELOG.md.meta
- UPM/samples_files/LICENSE.md.meta
- UPM/samples_files/NOTICE.md.meta
- UPM/samples_files/package.json
- UPM/samples_files/package.json.meta
Includes re-instating the fix for MRTK spatial mesh observer with XR SDK.
Also fixes up the meta files between core and samples.
> Fixes for the next release/feature tool publish

- Assets/WorldLocking.Core/Scripts/XR/AnchorManagerXR.cs
Fixes problem when two XR plugins are both installed (but only one is really active).
> Improved search for active ARAnchorSubsystem.

- Assets/WorldLocking.Core/Microsoft.MixedReality.WorldLocking.Core.asmdef
- Assets/WorldLocking.Core/Scripts/ARCore/AnchorManagerARCore.cs
- Assets/WorldLocking.Core/Scripts/ARF/AnchorManagerARF.cs
- Assets/WorldLocking.Core/Scripts/AnchorManager.cs
- Assets/WorldLocking.Core/Scripts/IAnchorManager.cs
- Assets/WorldLocking.Core/Scripts/Null/AnchorManagerNull.cs
- Assets/WorldLocking.Core/Scripts/WSA/AnchorManagerWSA.cs
- Assets/WorldLocking.Core/Scripts/WorldLockingManager.cs
- Assets/WorldLocking.Core/Scripts/XR/AnchorManagerXR.cs
- Assets/WorldLocking.Core/Scripts/XR/AnchorManagerXR_2018.cs
- Assets/WorldLocking.Core/Scripts/XR/AnchorManagerXR_2018.cs.meta
* Provides public property on IAnchorManager to query whether persistence is supported.
> Implement persistence on HL with XR SDK (OpenXR)

- Assets/WorldLocking.Core/Scripts/WorldLockingManager.cs
- UPM/core_files/package.json
- UPM/samples_files/package.json
Requires upping the version to v1.2.6.
> Temp workaround for FeatureTool category issue. 

- Assets/WorldLocking.Core/Editor/WorldLockingContextEditor.cs
- Assets/WorldLocking.Core/Microsoft.MixedReality.WorldLocking.Core.asmdef
- Assets/WorldLocking.Core/Scripts/AlignmentManager.cs
- Assets/WorldLocking.Core/Scripts/WorldLockingManager.cs
- Assets/WorldLocking.Core/Scripts/XR/AnchorManagerXR.cs
- Assets/WorldLocking.Core/Scripts/XR/AnchorManagerXR_OpenXR.cs
- Assets/WorldLocking.Core/Scripts/XR/AnchorManagerXR_OpenXR.cs.meta
- Assets/WorldLocking.Core/Scripts/XR/AnchorManagerXR_WMR.cs
- Assets/WorldLocking.Core/Scripts/XR/AnchorManagerXR_WMR.cs.meta
- Assets/WorldLocking.Tools/Scripts/StatusToText.cs
- UPM/core_files/CHANGELOG.md
- UPM/core_files/package.json
- UPM/samples_files/CHANGELOG.md
- UPM/samples_files/package.json
This is very similar to, and shares code with, the OpenXR plugin persistence path.
Fixes #137
> Persistence via WMR XR plugin

- Assets/WorldLocking.Core/Scripts/WorldLockingManager.cs
- UPM/core_files/CHANGELOG.md
- UPM/core_files/package.json
- UPM/samples_files/CHANGELOG.md
- UPM/samples_files/package.json
- UPM/upm_pack.cmd
Version needs to go up to repackage for missing .meta file for Frozen World Engine DLL.
.unitypackage and get direct from git are unaffected.
> Up version to fix UPM packaging issue

- Assets/WorldLocking.Core/Scripts/AlignmentManager.cs
- Assets/WorldLocking.Core/Scripts/WorldLockingManager.cs
* Also bump Patch version.
This fixes a failure to load a previous session in the [QRSpacePins sample](https://github.com/microsoft/MixedReality-WorldLockingTools-Samples/issues/42).
> Fix timing issue on AlignmentManager.Save

- UPM/core_files/CHANGELOG.md
- UPM/core_files/package.json
- UPM/samples_files/CHANGELOG.md
- UPM/samples_files/package.json
Nothing to affect CI, just packaging.
> Update packaging to v1.3.4

- UPM/core_files/CHANGELOG.md
- UPM/core_files/package.json
- UPM/samples_files/CHANGELOG.md
- UPM/samples_files/package.json
> Update packaging files for WLT v1.3.5.

- Assets/WorldLocking.Tools/Editor/WorldLocking.Tools.Editor.asmdef
> Add define so system knows if XRSDK is in play.

- README.md
Something is breaking online formatting.
> Try adding some blank lines at end of README.md

- Assets/WorldLocking.Core/Editor/WorldLockingContextEditor.cs
- Assets/WorldLocking.Core/Scripts/ARF.meta
- Assets/WorldLocking.Core/Scripts/ARF/AnchorManagerARF.cs
- Assets/WorldLocking.Core/Scripts/ARF/AnchorManagerARF.cs.meta
- Assets/WorldLocking.Core/Scripts/ARF/AnchorManagerARF_2019.cs
- Assets/WorldLocking.Core/Scripts/ARF/AnchorManagerARF_2019.cs.meta
- Assets/WorldLocking.Core/Scripts/ARF/SpongyAnchorARF.cs
- Assets/WorldLocking.Core/Scripts/ARF/SpongyAnchorARF.cs.meta
- Assets/WorldLocking.Core/Scripts/ARF/SpongyAnchorARF_2019.cs
- Assets/WorldLocking.Core/Scripts/ARF/SpongyAnchorARF_2019.cs.meta
- Assets/WorldLocking.Core/Scripts/AnchorManager.cs
- Assets/WorldLocking.Core/Scripts/AnchorSettings.cs
- Assets/WorldLocking.Core/Scripts/IAnchorManager.cs
- Assets/WorldLocking.Core/Scripts/WorldLockingManager.cs
- Assets/WorldLocking.Tools/Editor/WorldLockingSetup.cs
- README.md
Includes auto configuration if the scene is already configured for AR Foundation, i.e. has Session and Session Origin nodes.
> AR Foundation support

- Assets/WorldLocking.Tools/Scripts/SimpleConsole.cs
Very helpful on Android with LogCat limitations.
> Add optional log file to SimpleConsole. 

- DocGen/Documentation/HowTos/Samples/WLT_ASA_Sample.md
- DocGen/Documentation/HowTos/UsingWLT/JustWorldLock.md
- DocGen/Documentation/HowTos/WLTviaMRFeatureTool.md
Especially around installing WLT+ASA using MR Feature Tool.
> Documentation fixups.

- DocGen/Documentation/HowTos/CodingConventions.md
- DocGen/Documentation/HowTos/Samples/WLT_ASA_Sample.md
- DocGen/Documentation/HowTos/Tools.md
- DocGen/Documentation/HowTos/WLTviaMRFeatureTool.md
> Documentation tweaks for upcoming release

- Assets/WorldLocking.ASA/Prefabs/AnchorPrefab.prefab
Make anchor prefab (used for visualizing ASA) transparent and ignore
> Improve anchors prefab

- Assets/WorldLocking.ASA.Examples/Scripts/PlatformMenuSelector.cs
- Assets/WorldLocking.ASA/Scripts/PublisherASA.cs
- Assets/WorldLocking.ASA/Scripts/SpacePinBinder.cs
- Assets/WorldLocking.Core/Scripts/ARCore/SpongyAnchorARCore.cs
- Assets/WorldLocking.Core/Scripts/ARF/AnchorManagerARF.cs
- Assets/WorldLocking.Core/Scripts/ARF/AnchorManagerARF_2019.cs
- Assets/WorldLocking.Core/Scripts/ARF/AnchorManagerARF_OpenXR.cs
- Assets/WorldLocking.Core/Scripts/ARF/SpongyAnchorARF.cs
- Assets/WorldLocking.Core/Scripts/AlignSubtree.cs
- Assets/WorldLocking.Core/Scripts/AlignmentManager.cs
- Assets/WorldLocking.Core/Scripts/AnchorManager.cs
- Assets/WorldLocking.Core/Scripts/AnchorSettings.cs
- Assets/WorldLocking.Core/Scripts/Null/AnchorManagerNull.cs
- Assets/WorldLocking.Core/Scripts/SpacePin.cs
- Assets/WorldLocking.Core/Scripts/WorldLockingManager.cs
- Assets/WorldLocking.Core/Scripts/XR/AnchorManagerXR.cs
- Assets/WorldLocking.Core/Scripts/XR/AnchorManagerXR_2018.cs
- Assets/WorldLocking.Core/Scripts/XR/AnchorManagerXR_OpenXR.cs
- Assets/WorldLocking.Core/Scripts/XR/AnchorManagerXR_WMR.cs
- Assets/WorldLocking.Core/Scripts/XR/SpongyAnchorXR.cs
- Assets/WorldLocking.Engine/PluginNoop.cs
- Assets/WorldLocking.Tools/Editor/WorldLockingSetup.cs
- UPM/asa_files/CHANGELOG.md
- UPM/asa_files/package.json
- UPM/asa_samples_files/CHANGELOG.md
- UPM/asa_samples_files/package.json
- UPM/core_files/CHANGELOG.md
- UPM/core_files/package.json
- UPM/samples_files/CHANGELOG.md
- UPM/samples_files/package.json
Disable all WLT logging with a single define, WLT_DISABLE_LOGGING.
This is most effectively defined at the project level, in Player Settings / Other Settings / Scripting Define Symbols.
* Also included is a fix for using the new local world locking feature with AR Foundation.
> WLT quiet mode

- Assets/WorldLocking.ASA/Scripts/PublisherASA.cs
- Assets/WorldLocking.Core/Scripts/WorldLockingManager.cs
Collision of conditional compilations.
> Fix debug string

- Assets/WorldLocking.ASA.Examples/Scripts/ScreenSpacer.cs
- Assets/WorldLocking.Core/Scripts/ARF/AnchorManagerARF.cs
- Assets/WorldLocking.Core/Scripts/ARF/AnchorManagerARF_2019.cs
- Assets/WorldLocking.Core/Scripts/ARF/SpongyAnchorARF_2019.cs
- Assets/WorldLocking.Core/Scripts/AlignSubtree.cs
- Assets/WorldLocking.Core/Scripts/FragmentManager.cs
- Assets/WorldLocking.Core/Scripts/WorldLockingManager.cs
- Assets/WorldLocking.Core/Scripts/XR/AnchorManagerXR.cs
- Assets/WorldLocking.Core/Scripts/XR/AnchorManagerXR_2018.cs
- Assets/WorldLocking.Examples/Scripts/PhysicsBeamSample.cs
- Assets/WorldLocking.Tools/Scripts/AnchorGraphVisual.cs
- UPM/asa_files/CHANGELOG.md
- UPM/asa_files/package.json
- UPM/asa_samples_files/CHANGELOG.md
- UPM/asa_samples_files/package.json
- UPM/core_files/CHANGELOG.md
- UPM/core_files/package.json
- UPM/samples_files/CHANGELOG.md
- UPM/samples_files/package.json
Primarily involves waiting on the remoting connection and startup of XR services at startup. (Thanks David Fields!)
Also includes a fix for ARF2019 (back ported from ARF2020).
Additionally, makes AlignSubtree component smarter about auto-save and load, specifically not to do them when persistence isn't supported by the platform.
Bumps WLT version to v1.5.2.
> Support for Holographic Remoting

- UPM/asa_files/CHANGELOG.md
- UPM/asa_files/package.json
- UPM/asa_samples_files/CHANGELOG.md
- UPM/asa_samples_files/package.json
- UPM/core_files/CHANGELOG.md
- UPM/core_files/package.json
- UPM/samples_files/CHANGELOG.md
- UPM/samples_files/package.json
> Update packaging files.

- Assets/WorldLocking.Examples/Materials/Checker.mat
- Assets/WorldLocking.Examples/Materials/Checker.mat.meta
- Assets/WorldLocking.Examples/Scenes/Vehicle.unity
- Assets/WorldLocking.Examples/Scripts/CircleCam.cs
- Assets/WorldLocking.Tools/Scripts/SpacePinPercentageVisualizer.cs
This is to better convey what is part of the vehicle, versus what is part of the virtual environment the vehicle is moving through, versus what is attached to the physical room the app is running in.
> Add more background parts to Vehicle demo

- Assets/WorldLocking.ASA/Scripts/PublisherASA.cs
Fixes #282 
This change explicitly waits for the AR Session to at least get to the Read state before making any ASA calls. This works around an issue where ASA sometimes crashes if the AR Session hasn't yet fully initialized. See the associated issue for details.
> Explicitly wait for AR Session when starting up PublisherASA.
