Assets/WorldLocking.Core/Scripts/AnchorManager.cs
ProjectSettings/ProjectSettings.asset

* Replace deprecated call to XR GetLocalPosition/Rotation with new GetNodeState API.
* Disable (unused) playmode tests for all assemblies.

Support Unity 2019

---

Assets/WorldLocking.Core/Scripts/Orienter.cs
Assets/WorldLocking.Core/Scripts/OrienterThreeBody.cs
Assets/WorldLocking.Core/Scripts/OrienterThreeBody.cs.meta
Assets/WorldLocking.Examples/Scenes/SpacePin.unity

*Capability:*
The existing Orienter class computes an implied orientation based on the positions of the SpacePinOrientables in the physical world. As a simplifying assumption, the orientation is limited to yaw (rotation about the gravity vector/Y-axis). This is mostly simplifying for the application using the feature. Most applications assume that the Y-axis remains aligned with the gravity vector (e.g. when placing a billboard), and would be inconvenienced by WLT rotating space to break that assumption.
The new IOrienter class, OrienterThreeBody, does away with that simplification and computes a full 3-DOF rotation (rotation about all 3 axes). In particular, for slight corrections to pitch and roll to align a model with its physical counterpart, the negatives of the Y-axis no longer …

3-DOF implicit orientation computation

---

Assets/WorldLocking.Core/Scripts/IOrienter.cs
Assets/WorldLocking.Core/Scripts/Orienter.cs
Assets/WorldLocking.Core/Scripts/SpacePin.cs
Assets/WorldLocking.Core/Scripts/SpacePinOrientable.cs
Assets/WorldLocking.Core/Scripts/WorldLockingManager.cs
Assets/WorldLocking.Examples/Scenes/SpacePin3Body.unity
Assets/WorldLocking.Examples/Scripts/SpacePinOrientableManipulation.cs

The SpacePinOrientation family of space pins computes the implicit orientation from the positions of the active space pins.
That requires at least two space pins to be active, in order for there to be an implied orientation.
Previously, when only a single pin had its position set, the system would use an identity rotation until the required second pin was set.
With this addition, if there is an explicit rotation set on the first pin, that will be used until a second pin's position provides an implied rotation.
This involved a small refactor which seems an improvement on its own (although doesn't provide functional change).

Allow explicit rotation setting on first auto-oriented space pin.

---

Assets/WorldLocking.Core/Scripts/SpacePinOrientable.cs
Assets/packages.config

If iorienter set from script is of appropriate type (dervies from Orienter), also set it to the serialized orienter field. This is specifically for setting the iorienter from script in Editor, to allow the edited SpacePinOrientable to have its orienter serialized.
This PR also upgrades to the latest FW DLL, which includes a good fix for an obscure condition.
Fixes #47

Enable serialization of Orienter set from script

---

Assets/packages.config

NOTE: skipping 0.5.2 because of inadvertent lib dependency.
This engine DLL update fixes an issue where the DLL fails due to internal state corruption. It manifests as the system going into a state of constant "Refreeze indicated", performing a refreeze every frame (if auto-refreeze is enabled), all the while with the spongy and frozen worlds drifting apart. The drift apart is most visible, if using the AnchorVisualizer, by long red error bars extending from the spongy anchors to the frozen anchors.
No API changes are involved, and no other action by consuming application is required beyond updating to the latest engine DLL.

Update to DLL v0.5.3 

---

Assets/WorldLocking.Core/Scripts/AlignSubtree.cs

Field is redundant with and conflicts with WorldLockingManager.AutoSave/AutoLoad. As it doesn't enable any new behavior, removing for simplicity.

Remove redundant AutoSave field from AlignSubtree script

---

Assets/WorldLocking.Core/Scripts/SpacePin.cs
Assets/WorldLocking.Examples/Scripts/SpacePinManipulation.cs
Assets/WorldLocking.Examples/Scripts/SpacePinOrientableManipulation.cs
Assets/WorldLocking.Tests/Core/Scripts/AlignmentManagerTest.cs
Assets/WorldLocking.Tools/Scripts/AdjusterFixed.cs
Assets/WorldLocking.Tools/Scripts/AdjusterMoving.cs
DocGen/Documentation/Concepts/Advanced/AttachmentPoints.md
DocGen/Documentation/Concepts/Advanced/RefitOperations.md

The transform remains the preferred interface for retrieving the model position for a SpacePin, but there are situations when the transform is inappropriate.
Specifically, when a model's transforms have been "baked" into the geometry during export from a modeling package or import into Unity, then while the position information for a marker object is still available in the vertex data, the position in the transform is now meaningless.
In those cases, a position might still be extracted from the world bounds of either the object's renderer, or the object's collider.
This change allows the application to specify the source of the SpacePin's model position, as one of:
1. Transform's world-space position - transform.position
2. Renderer's world-space bounds - renderer.bounds.center
3. …

Space pin position by bounds

---

Assets/WorldLocking.Core/Scripts/AlignmentManager.cs

Protect against duplicating an AlignmentAnchor with redundant loads.

---

Assets/MRTK/Providers/XRSDK/GenericXRSDKSpatialMeshObserver.cs
Assets/WorldLocking.Core/Editor/WorldLockingContextEditor.cs
Assets/WorldLocking.Core/Scripts/ARF/AnchorManagerARF.cs
Assets/WorldLocking.Core/Scripts/AnchorManager.cs
Assets/WorldLocking.Core/Scripts/AnchorSettings.cs
Assets/WorldLocking.Core/Scripts/IAnchorManager.cs
Assets/WorldLocking.Core/Scripts/Null/AnchorManagerNull.cs
Assets/WorldLocking.Core/Scripts/WorldLockingManager.cs
Assets/WorldLocking.Core/Scripts/XR/AnchorManagerXR.cs
Assets/WorldLocking.Core/Scripts/XR/SpongyAnchorXR.cs
Assets/WorldLocking.Tests/Core/Scripts/WorldLockingManagerTest.cs
Assets/WorldLocking.Tools/Scripts/AnchorGraphVisual.cs
DocGen/Documentation/HowTos/WorldLockingContext.md

For large spaces and at the usual density of anchor placement, WLT can bog down performance by creating more WorldAnchors than the device is capable of processing under budget.
The processing of the anchor graph has still never shown up as a significant percentage of each frame's CPU usage. But each WorldAnchor in the scene incurs some processing cost, whether it is contributing to the world-locking or not.
To combat this, the user is given two degrees of freedom to explore trading off higher performance for (possibly) lower accuracy.
The first is to lower the density of the internal anchor graph. This is done via increasing the distance between anchor nodes with the MinNewAnchorDistance. The longer the edge length, the lower the density of anchors, and so the fewer anchors required to …

Option to limit the number of internal local anchors

---

Assets/MRTK/Providers/WindowsMixedReality/XR2018/WindowsMixedRealityEyeGazeDataProvider.cs

This fix has been merged into MRTK's mrtk_development, with target release of v2.6.0.
Fixes #102

Backport fix for eye gaze ignoring playspace.

---

Assets/WorldLocking.Core/Scripts/AlignSubtree.cs
Assets/WorldLocking.Core/Scripts/AlignmentManager.cs
Assets/WorldLocking.Core/Scripts/IAlignmentManager.cs
Assets/WorldLocking.Core/Scripts/WorldLockingManager.cs
Assets/WorldLocking.Tools/Scripts/SpacePinMeshVisualizer.cs

Allow visualization of multiple Space Pin groups (AlignSubtrees). Fixes #90 
Allow visualization of global Space Pin (WorldLockingManager's AlignmentManager).
> NOTE: This is a breaking change. The previous behavior found the first AlignSubtree in the scene (indeterminate), and visualized that with a global visualizer instance. A SpacePinVisualizer without its Target Subtree field set will now visualize the global AlignmentManager's SpacePins, rather than picking an AlignSubtree from the scene.

Fixup the space pin visualizer.

---

Assets/WorldLocking.Core/Scripts/ARCore/SpongyAnchorARCore.cs

Restore important change apparently lost in a merge somewhere, the step that actually pushes the updated pose from the internal anchor to the public (and functional) spongy anchor.

Change lost in merge?

---

Assets/WorldLocking.Core/Scripts/AnchorManager.cs
Assets/WorldLocking.Core/Scripts/SpongyAnchor.cs
Assets/WorldLocking.Core/Scripts/WSA/AnchorManagerWSA.cs
Assets/WorldLocking.Core/Scripts/WSA/SpongyAnchorWSA.cs
Assets/WorldLocking.Core/Scripts/WorldLockingManager.cs
Assets/WorldLocking.Tests/Core/Scripts/SaveLoadTest.cs
Assets/WorldLocking.Tools/Scripts/FrozenSpatialMapping.cs
Assets/WorldLocking.Tools/Scripts/FrozenTapToAdd.cs
Assets/WorldLocking.Tools/Scripts/ToggleWorldAnchor.cs

No functional change, but excludes Legacy WSA (removed from Unity 2020) code from compilation.
XRSDK anchor management supported (don't forget to change Anchor Management setting in World Locking Context!).
Fixes #114

Use defines to proof against lack of Legacy WSA in Unity 2020.

---

UPM/samples_files/CHANGELOG.md.meta
UPM/samples_files/LICENSE.md.meta
UPM/samples_files/NOTICE.md.meta
UPM/samples_files/package.json.meta

This is to to avoid collisions with tools package.
Fixes #125

Give the samples package its own meta files 

---

UPM/upm_pack.cmd

If the branch is clean, then `nuget restore` can be used to install the Frozen World Engine DLL, but .meta files for it won't be generated until Unity is run on that project.

Add a note about running Unity to generate .meta files before packaging.

---

UPM/upm_pack.cmd

The nuget package used to install the FW Engine DLL was getting packaged into the UPM package. Since the UPM package just needs the unpacked dlls, this was basically doubling the size of the UPM package with the redundancy.

Remove redundant nuget package from UPM package.

---

Assets/WorldLocking.Tools/Editor/WorldLockingSetup.cs

Otherwise changes will be discarded after unloading scene.

Mark context and scene as dirty after modification from editor script.

---

Assets/MRTK/Providers/XRSDK/GenericXRSDKSpatialMeshObserver.cs

This applies the following PR into the MRTK snapshot of v2.6.1 included with the examples.
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9819

MRTK Fix for XRSDK spatial meshes.

---

Assets/WorldLocking.Core/Scripts/WorldLockingManager.cs
Assets/packages.config

Note that when you get this update, if you are NOT using NuGet for Unity, you need to delete everything in your Assets/Packages/Microsoft.MixedReality.Unity.FrozenWorld folder. See instructions for [updating Frozen World Engine DLL here](https://microsoft.github.io/MixedReality-WorldLockingTools-Unity/DocGen/Documentation/HowTos/InitialSetup.html#manual-frozen-world-engine-dll-installation).

Update to Frozen World Engine v1.1.1

---

Assets/WorldLocking.ASA/Scripts/IPublisher.cs
Assets/WorldLocking.ASA/Scripts/PublisherASA.cs
Assets/WorldLocking.ASA/Scripts/SpacePinBinder.cs

Working, tested HL2 & Android. 
Motivation for this is that there is significant time overhead to querying ASA for one or more cloud anchor ids. While the time required querying N ids one by one is on the order of a N minutes (N * ~40seconds), querying for N ids on a single watcher is roughly constant time (~40 seconds).
Making find by list default used by SpacePinBinder.

Add Read list of cloud anchors to IPublisher API

---

Assets/WorldLocking.ASA.Examples/Scenes/PinTestSofa.unity
Assets/WorldLocking.ASA/Scripts/PublisherASA.cs
Assets/WorldLocking.Core/Scripts/ARF/AnchorManagerARF.cs
Assets/WorldLocking.Core/Scripts/ARF/SpongyAnchorARF.cs
Assets/WorldLocking.Core/Scripts/WorldLockingManager.cs
Assets/WorldLocking.Core/Scripts/XR/AnchorManagerXR.cs
DocGen/Documentation/HowTos/Samples/WLT_ASA_Sample.md
UPM/asa_files/CHANGELOG.md
UPM/asa_files/package.json
UPM/asa_samples_files/CHANGELOG.md
UPM/asa_samples_files/package.json
UPM/core_files/CHANGELOG.md
UPM/core_files/package.json
UPM/samples_files/CHANGELOG.md
UPM/samples_files/package.json

OpenXR is now returning a session subsystem, but the session always (incorrectly) reports tracking state = TrackingState.None. 
Previous OpenXR issue was that no session subsystem was found.
Workaround is to leave session subsystem null, which will ignore its (incorrect) tracking state.
Additionally, this PR includes a workaround for a race condition caused by recent changes in ASA.
Also includes use of new API for creating anchors within the AR Foundation framework.

Workaround for new OpenXR issue. 

---

Assets/WorldLocking.Core/Scripts/AnchorManager.cs
Assets/WorldLocking.Core/Scripts/WorldLockingManager.cs
Assets/WorldLocking.Core/Scripts/XR/AnchorManagerXR.cs

The MR OpenXR session subsystem needs to be updated externally. The ARSession component performs this manual pumping of the subsystem in its monobehavior Update() function.
When not using ARFoundation, however, subsystems with Update functions must be updated by some other agent. Some of them are updated by MRTK, but not the XRSessionSubsystem.
The WMR XR Plugin doesn't seem to require this update. It is difficult to say whether the mobile platforms require it, as MRTK adds some AR Foundation elements to get mobile to work. If the Update is redundant, it doesn't seem to hurt anything in tests so far.
If it does, then we might need to push responsibility onto the application, either requiring them to call XRSessionSubsystem.Update() when appropriate, or adding a checkbox letting them tell …

Adjust for OpenXR session subsystems special needs.

---

Assets/WorldLocking.Core/Editor/WorldLockingContextEditor.cs
Assets/WorldLocking.Core/Scripts/AlignSubtree.cs
Assets/WorldLocking.Core/Scripts/AlignmentManager.cs
Assets/WorldLocking.Core/Scripts/IOrienter.cs
Assets/WorldLocking.Core/Scripts/LinkageSettings.cs
Assets/WorldLocking.Core/Scripts/Orienter.cs
Assets/WorldLocking.Core/Scripts/SpacePin.cs
Assets/WorldLocking.Core/Scripts/SpacePinOrientable.cs
Assets/WorldLocking.Core/Scripts/WorldLockingManager.cs
Assets/WorldLocking.Examples/Scripts/SpacePinManipulation.cs
Assets/WorldLocking.Examples/Scripts/SpacePinOrientableManipulation.cs
Assets/WorldLocking.Tools/Editor/WorldLockingSetup.cs
Assets/WorldLocking.Tools/Scripts/AnchorGraphVisual.cs
Assets/WorldLocking.Tools/Scripts/SpacePinMeshVisualizer.cs
UPM/asa_files/CHANGELOG.md
UPM/asa_files/package.json
UPM/asa_samples_files/CHANGELOG.md
UPM/asa_samples_files/package.json
UPM/core_files/CHANGELOG.md
UPM/core_files/package.json
UPM/samples_files/CHANGELOG.md
UPM/samples_files/package.json
UPM/upm_pack.cmd

Allow the restriction of world locking to local subtrees, while still getting full world locking.
While some benefits of WLT will be unavailable (e.g. world locking of non-movable items such as particle systems, nav meshes, etc), this allows parts of an application to gain benefits of world locking without restructuring other parts.
For new projects, it is still strong recommended to apply WLT globally, along with possible additional pinning of subtrees.
Fixes #201

Support local world locking

---

Assets/WorldLocking.ASA/Scripts/PublisherASA.cs
Assets/WorldLocking.ASA/Scripts/SpacePinBinderFile.cs
Assets/WorldLocking.Core/Scripts/OrienterThreeBody.cs
Assets/WorldLocking.Core/Scripts/WorldLockingManager.cs
Assets/WorldLocking.Tools/Scripts/SimpleConsole.cs
UPM/asa_files/CHANGELOG.md
UPM/asa_files/package.json
UPM/asa_samples_files/CHANGELOG.md
UPM/asa_samples_files/package.json
UPM/core_files/CHANGELOG.md
UPM/core_files/package.json
UPM/samples_files/CHANGELOG.md
UPM/samples_files/package.json

Fixes #217 
Also includes a 1-frame delay to workaround ASA anchors sometimes not being ready immediately after creation.

Backward compat for Unity 2018 .NET backend

---

Assets/WorldLocking.ASA.Examples/Scenes/PinTest.unity
Assets/WorldLocking.ASA.Examples/Scenes/PinTestSofa.unity

MRTK looks for a GameObject named "AR Session", and then looks for the ARSession component on that node. If it doesn't find the node by name, or doesn't find the component on it, it creates a new ARSession component and adds it to the scene.
This change allows MRTK to find the extant ARSession component so it won't create a redundant one. This can have very large performance ramifications, seen on Android Galaxy.

Setup "AR Session" node for compatibility with MRTK.

---

UPM/asa_files/package.json
UPM/asa_samples_files/package.json

Earlier versions seem to have been broken by a Unity or OS update. See #240

Up ASA dependencies to ASA v2.11.0

---

Assets/WorldLocking.ASA/Scripts/PublisherASA.cs
Assets/WorldLocking.ASA/Scripts/SpacePinBinder.cs
Assets/WorldLocking.Core/Editor/WorldLockingContextEditor.cs
Assets/WorldLocking.Core/Scripts/AnchorManager.cs
Assets/WorldLocking.Core/Scripts/LinkageSettings.cs
Assets/WorldLocking.Core/Scripts/WorldLockingManager.cs
Assets/WorldLocking.Tools/Scripts/AnchorGraphVisual.cs
Assets/WorldLocking.Tools/Scripts/SpongyAnchorVisual.cs
UPM/asa_files/CHANGELOG.md
UPM/asa_files/package.json
UPM/asa_samples_files/CHANGELOG.md
UPM/asa_samples_files/package.json
UPM/core_files/CHANGELOG.md
UPM/core_files/package.json
UPM/samples_files/CHANGELOG.md
UPM/samples_files/package.json

* Improve anchor stability by creating them at camera position, rather than the traditional 1 meter down.
* Add vertical offset parameter on the AnchorGraphVisual to optionally display anchors lower or higher than their actual position, to allow avoidance of anchor visuals at eye level.
* Fix a compatibility issue with ASA v2.11, removing a workaround for an ASA issue needed for earlier versions, but harmful for v2.11.

Raise creation point of underlying anchors

---

Assets/WorldLocking.Engine/PluginNoop.cs

It seems more suitable to log this as warning, since the back end has already been selected (perhaps on purpose), so this may not be an error at all.
Additionally, logging errors will cause Unity scene tests to fail, as error logs are treated as test failure. This can be ignored by updating the test, but it could require updating every test (e.g. our scene contains the world locking tools and the noop backend immediately constructs when running in CI on a Linux Unity environment).

Log warning in PluginNoop instead of Error to avoid breaking tests

---

Assets/WorldLocking.Examples/Scenes/Vehicle.unity
Assets/WorldLocking.Examples/Scenes/Vehicle.unity.meta
Assets/WorldLocking.Examples/Scripts/CircleCam.cs
Assets/WorldLocking.Examples/Scripts/CircleCam.cs.meta

The Vehicle sample scene is a stripped down version of attaching a camera to a vehicle or platform.
As the root of the camera tree is moved through Unity's global coordinate space, the global coordinates of the camera are constantly changing. Naturally, this doesn't move the camera through physical space. The camera is moving through virtual space, but not through physical space.
Other things attached to the moving root also moving with the camera. From the camera's perspective, the other things moving with it (also attached to moving root) are stationary, and the stationary things in global space appear to be moving. So the things also attached to moving root can be thought of as parts of the vehicle in which the camera is riding. The things stationary in global space that are moving by …

Add sample for vehicle type configuration

---

Assets/WorldLocking.Core/Microsoft.MixedReality.WorldLocking.Core.asmdef
Assets/WorldLocking.Core/Scripts/ARF/AnchorManagerARF_OpenXR.cs
Assets/WorldLocking.Core/Scripts/WorldLockingManager.cs
Assets/WorldLocking.Core/Scripts/XR/AnchorManagerXR_OpenXR.cs

Adopt new persistence APIs for MROpenXR when version is greater or equal to 1.4.0.
Specifically, replace deprecated XRAnchorStore.LoadAsync() with ARAnchorManager and XRAnchorSubsystem extensions LoadAnchorStoreAsync().
Also bumps version from 1.5.9 (last release) to 1.5.10_dev.

Persistence changes in MROpenXR
